### ISSUE TITLE
Remove php source

### ISSUE THREAD

**Issue by SerafimArts** [spiral/goridge#101]
All source code has been moved to a separate repository: https://github.com/spiral/goridge-php

Required:
- [ ] Remove PHP sources
- [ ] Remove PHP dependencies (i.e. composer.json)
- [ ] Actualize CI and tests

**Comment by duckbrain** [comment]
Could we have some mention of this other repo in the README? This took me a little while to find.

**Comment by 48d90782** [comment]
> Could we have some mention of this other repo in the README? This took me a little while to find.

@duckbrain Sure, done https://github.com/spiral/goridge/blob/master/README.md
