### ISSUE TITLE
Сan`t find package v3

### ISSUE THREAD

**Issue by alexpts** [spiral/goridge#102]
Try install goridge
`go get -u github.com/spiral/goridge/v3`

Result:
`
cannot find package "github.com/spiral/goridge/v3" in any of:
        /usr/local/Cellar/go/1.15.7_1/libexec/src/github.com/spiral/goridge/v3 (from $GOROOT)
        /Users/alex/go/src/github.com/spiral/goridge/v3 (from $GOPATH)
`

**Comment by 48d90782** [comment]
@alexpts I have updated the package in the go.pkg, should now work. On the old 1.15 and older versions of the GOlang, use `GO111MODULE=on go get -u github.com/spiral/goridge/v3`

**Comment by 48d90782** [comment]
Feel free to reopen the issue if the problem is still exists
