### ISSUE TITLE
goridge RPC from fcgi (such as PHP-FPM)

### ISSUE THREAD

**Issue by ClosetMonkey** [spiral/goridge#152]
Hi, I've been skimming over Roadrunner and I've noticed that it supports fcgi. So, assuming Roadrunner is working as a http server and is sending requests to PHP-FPM over fcgi, can PHP script running in PHP-FPM land (say a WordPress plugin for example) issue rpc calls back to Roadrunner via goridge?

Many thanks 🙏

**Comment by ClosetMonkey** [comment]
After looking further i noticed that roadrunner is only capablr of acting as a fcgi listener/sever. However, my question is still the same overall: Can a PHP script being ran within PHP-FPM still issue goridge RPC commands to Roadrunner framework? (assuming they are both running on the same node)

**Comment by wolfy-j** [comment]
Yes, you can simply disable HTTP and other transport layers and only keep the RPC config.
