### ISSUE TITLE
Go To PHP

### ISSUE THREAD

**Issue by abshammeri** [spiral/goridge#25]
Just wondering if it's possible to use or modify this package to call php cli function from go? I have a go tcp server, I would like to pass the body to php cli and get back the response. I have several ways to implement it (such as STDIN) , but I'm not sure if you implement something like that.

Thanks

**Comment by wolfy-j** [comment]
Hi,

take a look at https://github.com/spiral/roadrunner as it doing exactly that. :) Also there is GRPC package coming, this will make RPC for PHP much accessible.
