### ISSUE TITLE
Sporadic connection timeout, debugging help needed.

### ISSUE THREAD

**Issue by jrots** [spiral/goridge#28]
Hi, 
I'm seeing a sporadic: "socket_connect(): unable to connect [110]: Connection timed out" fromout php to a go service running  goridge.
We're doing some calls per second but nothing not out of the ordinary, the load on the server is OK and I don't see any errors outputted in the service that is running, nor in dmesg. 

The timeouts occur in an internal network, so I don't suspect a networking issue. 
Is there a way to know when the server can't accept the request anymore f.e. too many goroutines are running?  (This would probably output an error I guess ) 
Or have some verbosity settings to know the number of running goridge requests?

Or are there other things I could do to have some more insight why it would trigger a connection time out in the first place?

Thanks a lot!
J

**Comment by wolfy-j** [comment]
What socket listener do you use on the Golang end? One from default implementation? Try to log how much open/closed connections do you have. Goridge is transport protocol, RPC server is managed on the side of your application.

Are you experiencing such issues after running your application for some time or right from the start of the server?
