### ISSUE TITLE
StreamRelay requires Sockets extension

### ISSUE THREAD

**Issue by batyrmastyr** [spiral/goridge#31]
I tried to add metrics into my application and hit into following error: 
```
roadrunner_1  | WARN[0020] Error: Call to undefined function Spiral\Goridge\socket_create() in /www/vendor/spiral/goridge/php-src/SocketRelay.php:275 
roadrunner_1  | WARN[0020] Stack trace:                                 
roadrunner_1  | WARN[0020] #0 /www/vendor/spiral/goridge/php-src/SocketRelay.php(185): Spiral\Goridge\SocketRelay->createSocket() 
roadrunner_1  | WARN[0020] #1 /www/vendor/spiral/goridge/php-src/SocketRelay.php(88): Spiral\Goridge\SocketRelay->connect() 
roadrunner_1  | WARN[0020] #2 /www/vendor/spiral/goridge/php-src/RPC.php(47): Spiral\Goridge\SocketRelay->send('metrics.Add\x00\x00\x00\x00...', 20) 
roadrunner_1  | WARN[0020] #3 /www/vendor/spiral/roadrunner/src/Metrics.php(44): Spiral\Goridge\RPC->call('metrics.Add', Array) 
roadrunner_1  | WARN[0020] #4 /www/psr-worker.php(29): Spiral\RoadRunner\Metrics->add('app_metric_coun...', 1) 
roadrunner_1  | WARN[0020] #5 {main}                                    
```
RR version is 1.4.7. 
The reason is inexisting Sockets extension.

Suggestion: to require it in composer.json as "ext/sockets" OR to mention it in documentation and to throw exception if (!extension_loaded('sockets')) in createSocket

P.S. There are also some json_encode in Spiral\Goridge\RPC, so it's better to add ext/json to require too.

**Comment by wolfy-j** [comment]
It actually says that in README `sockets over TCP or Unix (ext-sockets is required), standard pipes`, we would like not to make it required since RR can work over pipes in producer mode. We will correct the documentation. Thank you for the catch

**Comment by wolfy-j** [comment]
I have updated the documentation: https://roadrunner.dev/docs/usage-rpc

**Comment by c33s** [comment]
@wolfy-j i also stumpled upon this issue.

wouldn't it be possible to require `ext-socket` and use composers `platform` config or use `--ignore-platform-reqs`?

if i want to use it without the ext i could call it with `--ignore-platform-reqs` or add 
```
    "config": {
        "platform": {
            "ext-socket": "..."
        }
    },
```
to my project where i use this lib.

don't know if this would be possible, just an idea

**Comment by wolfy-j** [comment]
We will address this issue with the protocol update in the next version. I would avoid changing deps like that as it will affect a ton of users. :(
