### ISSUE TITLE
How to write golang client

### ISSUE THREAD

**Issue by tomener** [spiral/goridge#33]
I only see the PHP client. How can I write for the golang client?

php client
```
$rpc = new Goridge\RPC(new Goridge\SocketRelay("127.0.0.1", 6001));

echo $rpc->call("App.Hi", "Antony");
```

go client
How to write golang client?

**Comment by wolfy-j** [comment]
You can use the default net/rpc package with Goridge codec at the top. This is the example: 

https://github.com/spiral/roadrunner/blob/master/service/rpc/service.go#L113

**Comment by tomener** [comment]
Is that it?
https://github.com/spiral/goridge/blob/master/client_server_test.go#L81

**Comment by wolfy-j** [comment]
Yes.
