### ISSUE TITLE
STDIN is not readable

### ISSUE THREAD

**Issue by tarampampam** [spiral/goridge#36]
Since version `2.2.0` (after execution `composer update`) i'v got an error:

```
resource `in` must be readable in /app/vendor/spiral/goridge/php-src/StreamRelay.php:43
```

In my code, I create `StreamRelay` using  the following code:

```php
new \Spiral\Goridge\StreamRelay(\STDIN, \STDOUT);
```

And got an error, describet above. It happens because since version `2.2.0` this package uses next assert:

```php
    /**
     * Checks if stream is readable.
     *
     * @param resource $stream
     *
     * @return bool
     */
    private function assertReadable($stream): bool
    {
        $meta = stream_get_meta_data($stream);
        return in_array($meta['mode'], ['r', 'r+', 'w+', 'a+', 'x+', 'c+'], true);
    }
```

> Previos checking method was better: `$this->assertMode($in, 'r')`

But this method does not allows to use `binary safe` mode (`b`), which appended to the `STDIN` and `STDOUT` by default:

```bash
$ docker run --rm php:7.3.0-alpine php -r 'var_dump(stream_get_meta_data(\STDIN)["mode"]);'
string(2) "rb"

$ docker run --rm php:7.2.0-alpine php -r 'var_dump(stream_get_meta_data(\STDIN)["mode"]);'
string(2) "rb"
```

So, my applications cannot be started after update =(

**Comment by wolfy-j** [comment]
@zloyuser sounds like checks are too strict.
@tarampampam will address it today’s update.

**Comment by tarampampam** [comment]
@wolfy-j also file `CHANGELOG.md` does not contains release information

**Comment by wolfy-j** [comment]
Release and CHANGELOG fixes are out. Thx for your PR

**Comment by tarampampam** [comment]
@wolfy-j Wow, super-speed! Thx!
