### ISSUE TITLE
Allow Unix socket on Windows

### ISSUE THREAD

**Issue by oakad** [spiral/goridge#38]
Windows 10 now supports basic functionality of AF_UNIX sockets. Consequently, restriction on Unix sockets on Windows was removed in Go and thus can be removed in goridge.

**Comment by wolfy-j** [comment]
I don't think we are restricting UNIX sockets on Windows. They are only excluded in tests but the functionality is there.

**Comment by oakad** [comment]
https://github.com/spiral/goridge/blob/33e92c47f149ad266d62538cd69b98c051152cda/php-src/SocketRelay.php#L268

**Comment by wolfy-j** [comment]
Oops, you are right.

**Comment by wolfy-j** [comment]
If you can create PR I will be able to review it this week.

**Comment by 48d90782** [comment]
@oakad in master now.
