### ISSUE TITLE
RelayInterface should offer a static factory method

### ISSUE THREAD

**Issue by oakad** [spiral/goridge#39]
To simplify operation at low expense, `RelayInterface` could offer a static factory method to instantiate a new relay implementation based on concise description. Some examples:

`RelayInterface::make("pipes://0:1")` - return a new `StreamRelay` instance using file descriptors 0 and 1

`RelayInterface::make("tcp://localhost:1234")` - return a new `SocketRelay` instance connected to port 1234 on localhost.

Such a simple factory method will make goridge substantially friendlier to the user.

**Comment by wolfy-j** [comment]
I assume Relay, not RelayInterface. I agree about the proposal.
