### ISSUE TITLE
Error occurred .. Please help me.

### ISSUE THREAD

**Issue by minsoo5403** [spiral/goridge#40]
C:\Bitnami\wampstack-7.2.26-0\apache2\htdocs\kms>php index.php
PHP Fatal error:  Uncaught Error: Call to undefined function Spiral\Goridge\socket_create() in C:\Bitnami\wampstack-7.2.26-0\apache2\htdocs\kms\vendor\spiral\goridge\php-src\SocketRelay.php:275
Stack trace:
#0 C:\Bitnami\wampstack-7.2.26-0\apache2\htdocs\kms\vendor\spiral\goridge\php-src\SocketRelay.php(185): Spiral\Goridge\SocketRelay->createSocket()
#1 C:\Bitnami\wampstack-7.2.26-0\apache2\htdocs\kms\vendor\spiral\goridge\php-src\SocketRelay.php(88): Spiral\Goridge\SocketRelay->connect()
#2 C:\Bitnami\wampstack-7.2.26-0\apache2\htdocs\kms\vendor\spiral\goridge\php-src\RPC.php(47): Spiral\Goridge\SocketRelay->send('App.Hi\x00\x00\x00\x00\x00\x00\x00\x00', 20)
#3 C:\Bitnami\wampstack-7.2.26-0\apache2\htdocs\kms\index.php(8): Spiral\Goridge\RPC->call('App.Hi', 'Antony')
#4 {main}
  thrown in C:\Bitnami\wampstack-7.2.26-0\apache2\htdocs\kms\vendor\spiral\goridge\php-src\SocketRelay.php on line 275

**Comment by wolfy-j** [comment]
Make sure you have socket extension.

**Comment by minsoo5403** [comment]
It's working. Thank you.
