### ISSUE TITLE
Second call is too slow

### ISSUE THREAD

**Issue by swifft17** [spiral/goridge#41]
Hi.
I did:
go get "github.com/spiral/goridge"
composer require spiral/goridge
cd ~/go/src/goridge/vendor/spiral/goridge/examples
go run ./

And ran the folowing script:

`<?php
use Spiral\Goridge;
require "vendor/autoload.php";

$t1 = microtime(true);
$rpc = new Goridge\RPC(
  new Goridge\SocketRelay("127.0.0.1", 6001)
);
echo $rpc->call("App.Hi", "Antony");
$t3 = (float)microtime(true) - (float)$t1;

echo ": $t3 | ";
$t1 = microtime(true);
echo $rpc->call("App.Hi", "Antony");
$t2 = microtime(true);
$t3 = (float)$t2 - (float)$t1;
echo ": $t3" . PHP_EOL;`

I got a result:
Hello, Antony!: 0.**0007**1406364440918 | Hello, Antony!: 0.**0412**56904602051
Is it a bug? Or I made mistake?

** Thank for your job!

**Comment by wolfy-j** [comment]
What environment are you using? Is it Windows? Use unix sockets on Linux as much faster communication transport.

**Comment by swifft17** [comment]
Thanks.
I'm using Linux. On unix sockets I don't have this problem.

**Comment by wolfy-j** [comment]
Yeah, we are currently experiencing slowness with TCP on Linux. That will be addressed in a future release. Please stick to unix for now.

**Comment by 48d90782** [comment]
@vvval Could you please help here?
We need to reduce number of syscalls. In the src/RCP.php file, function `send`. 
```php
        !!! CONCATENATE THIS CALL
        $this->relay->send(
            $method . pack("P", $this->seq),
            Relay::PAYLOAD_CONTROL | Relay::PAYLOAD_RAW
        );

        if ($flags & Relay::PAYLOAD_RAW) {
            !!! WITH THIS
            $this->relay->send($payload, $flags);
        } else {
            $body = json_encode($payload);
            if ($body === false) {
                throw new Exceptions\ServiceException(sprintf(
                    "json encode: %s",
                    json_last_error_msg()
                ));
            }
            !!! AND THIS
            $this->relay->send($body);
        }
```
into one `send`.

**Comment by 48d90782** [comment]
@wolfy-j @swifft17 @vvval  `Hello, Antony!: 0.00073885917663574 | Hello, Antony!: 0.00010585784912109` Now the timestamps are almost the same.
