### ISSUE TITLE
Respect Semantic versioning? 

### ISSUE THREAD

**Issue by Reasno** [spiral/goridge#65]
I am curious why the new tag 2.4.0 breaks BC by bumping PHP to 7.2? It seems more like 3.0 via semantic versioning.

**Comment by wolfy-j** [comment]
Hi, Semver does not clearly specifies what to do when underlying dependency changes without changes in public API. It’s a huge debate here - https://github.com/semver/semver/issues/148

Our developers motivation was:
1) 7.1 lifecycle is over
2) you are free to use older versions of this package, they all a backward compatible with RR and etc
3) there are no API changes

Let me know if you disagree on your use case.

**Comment by Reasno** [comment]
I don't mind upgrading, but it certainly breaks lots of CI builds.

Also isn't RelayInterface part of the public API? That was changed too.

https://github.com/spiral/goridge/commit/1bbf3494aebcecddd60370d9bae10c299bfba041#diff-05d7d701f31f708c14712fdca7d6f44d

**Comment by wolfy-j** [comment]
Now I’m inviting @vvval @48d90782 to respond :)

**Comment by wolfy-j** [comment]
Can you let me know what CI builds break? Composer should not install the package if php version not met.

**Comment by 48d90782** [comment]
@Reasno According to the semver 2.0 https://semver.org/#spec-item-8 we should change the first digit only in case of changing public API.

**Comment by Reasno** [comment]
I added my own RelayInterface implementation. And the RelayInterface signature change in the 2.4.0 caused trouble. 

https://github.com/hyperf/gotask/blob/master/src/Relay/CoroutineSocketRelay.php

**Comment by 48d90782** [comment]
@Reasno Hm, ok, I see your problem. We will release 2.4.1 and remove BC in a few hours.

**Comment by vvval** [comment]
I assume one single change with a declared return type caused it

**Comment by vvval** [comment]
Improved tests that will guarantee no bc break, you can check the fixture [here](https://github.com/spiral/goridge/blob/83c8a87594f4ce9ed524ecd18733b560cf425987/tests/Cases/Legacy/Relay.php)

**Comment by Reasno** [comment]
Thanks!

**Comment by 48d90782** [comment]
@Reasno https://github.com/spiral/goridge/releases/tag/2.4.1

**Comment by Reasno** [comment]
> @Reasno https://github.com/spiral/goridge/releases/tag/2.4.1

👍👍👍
