### ISSUE TITLE
Getting ErrorException when the worker is stopped

### ISSUE THREAD

**Issue by sikhlana** [spiral/goridge#74]
In production whenever the worker is being terminated by Roadrunner normally or by stopping the main process, I am getting an `ErrorException` with the following message:

```
unpack(): Type C: not enough input, need 1, have 0
```

on line: https://github.com/spiral/goridge/blob/c522eec9d8215c6059eeb4647d37003a2726e346/src/StreamRelay.php#L152

Goridge version: `v2.4.4`
Roadrunner version: `v1.5.1`

**Comment by wolfy-j** [comment]
Can you try more recent versions of RR?

**Comment by sikhlana** [comment]
@wolfy-j just updated RR on local environment, same issue. Do note that I am using the roadrunner-laravel bridge for my project.

**Comment by wolfy-j** [comment]
Weird, graceful-stop should be handled correctly even for laravel. In general, this error should be harmless since you already stopping your server, but we will double check in upcoming releases.

**Comment by 48d90782** [comment]
Similar to the #77 , also was fixed in Goridge3 and RR2. Feel free to reopen the issue if the problem still exists in those versions.
